name: WakaTime Stats

on:
  schedule:
    # Runs at every hour
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.key }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_user: current
          plugin_wakatime_days: 30
