name: WakaTime Stats

on:
  schedule:
    # Runs at 12 am UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.key }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TOTAL: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_TIME: "True"
          THEME: "synthwave"
          SECTION_NAME: "waka"
          LANG_COUNT: 10
          IGNORED_LANGUAGES: "AI vs Human"
